# Generated by Django 2.0.7 on 2019-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text1', models.IntegerField()),
                ('text2', models.IntegerField()),
                ('text3', models.IntegerField()),
                ('text4', models.IntegerField()),
                ('text5', models.IntegerField()),
                ('text6', models.IntegerField()),
                ('text7', models.IntegerField()),
                ('text8', models.IntegerField()),
                ('text9', models.IntegerField()),
            ],
        ),
    ]
