# Generated by Django 2.0.7 on 2019-10-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggers',
            name='title',
            field=models.CharField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
